version: '3.8'

services:
  app:
    container_name: nestjs_survey_api
    build: .
    command: npm run start:dev
    ports:
      - 3333:3000
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=survey
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "saulo.braga@live.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "8000:80"
    depends_on:
      - postgres